<template>
    <v-form ref="form" v-model="valid" lazy-validation>
        <v-text-field v-model="fname" :counter="10" :rules="nameRules" label="First Name" required></v-text-field>

        <v-text-field v-model="lname" :counter="10" :rules="nameRules" label="Last Name" required></v-text-field>

        <v-text-field v-model="email" :rules="emailRules" label="E-mail" required></v-text-field>

        <v-text-field v-model="phone" :rules="phoneRules" label="Phone" required></v-text-field>

        <!--<v-select v-model="select" :items="items" :rules="[v => !!v || 'Item is required']" label="Item" required>
        </v-select>-->

        <!--<v-checkbox v-model="checkbox" :rules="[v => !!v || 'You must agree to continue!']" label="Do you agree?"
            required></v-checkbox>-->

        <v-btn :disabled="!valid" color="success" class="mr-4" @click="submit">
            Submit
        </v-btn>

        <v-btn color="warning" class="mr-4" @click="reset">
            Reset Form
        </v-btn>

        <!--<v-btn color="warning" @click="resetValidation">
            Reset Validation
        </v-btn>-->
    </v-form>
</template>

<script setup>
import { useAnalytics } from '~/stores/analytics.js'
const analytics = useAnalytics()

const form = ref(null)
const valid = ref(true)
const fname = ref('')
const lname = ref('')
const nameRules = [
    v => !!v || 'Name is required',
    v => (v && v.length <= 10) || 'Name must be less than 10 characters',
]
const email = ref('')
const emailRules = [
    v => !!v || 'E-mail is required',
    v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
]

const phone = ref('')

const phoneRules = [
    v => !!v || 'Phone is required',
    v => /^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/.test(v) || 'Phone must be valid',
]

/*const select = ref(null)
const items = [
    'Item 1',
    'Item 2',
    'Item 3',
    'Item 4',
]
const checkbox = ref(false)*/

const traitsObject = computed(() => {
    return {
        fname: fname.value,
        lname: lname.value,
        email: email.value,
        phone: phone.value
    }
})

const user_id = computed(() => fname.value + '_' + lname.value + '_id') // would be generated by backend db

function submit() {
    if (form.value.validate()) {
        analytics.identify(user_id.value, traitsObject.value)
    } else {
        // go to error page
    }
}

function reset() {
    form.value.reset()
}

function resetValidation() {
    form.value.resetValidation()
}
</script>

<style lang="scss" scoped>

</style>