<script setup>
import { useAnalytics } from '~/stores/analytics.js'
const analytics = useAnalytics()

const form = ref(null)
const valid = ref(true)
const user_id = ref('')
const phone = ref('')
/*const nameRules = [
    v => !!v || 'Name is required',
    v => (v && v.length <= 10) || 'Name must be less than 10 characters',
]
const email = ref('')
const emailRules = [
    v => !!v || 'E-mail is required',
    v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
]

const phone = ref('')

const phoneRules = [
    v => !!v || 'Phone is required',
    v => /^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/.test(v) || 'Phone must be valid',
]*/

/*const select = ref(null)
const items = [
    'Item 1',
    'Item 2',
    'Item 3',
    'Item 4',
]
const checkbox = ref(false)*/

const traitsObject = computed(() => {
    return {
        /*fname: fname.value,
        lname: lname.value,
        email: email.value,
        phone: phone.value*/
    }
})

//const user_id = computed(() => fname.value + '_' + lname.value + '_id') // would be generated by backend db

function prePop() {
    user_id.value = 'Andy_Cogbill_id'
    phone.value = '146-765-2592'
    /*email.value = 'andycogbill@gmail.com'
    phone.value = "608-788-7808"*/
}

function submit() {
    if (form.value.validate()) {
        // analytics.userID = user_id.value
        analytics.loginWithTraits({ phone: phone.value })
        // analytics.track("Signed In")
    } else {
        // go to error page
    }
}

function reset() {
    form.value.reset()
}

function resetValidation() {
    form.value.resetValidation()
}
</script>

<template>
    <v-card>
        <v-card-title>
            <h5 class="branded">Customer Lookup</h5>
        </v-card-title>

        <v-form ref="form" v-model="valid" lazy-validation>
            <v-card-text>
                <!-- <v-text-field v-model="user_id" :counter="10" label="User ID" required>
                </v-text-field> -->

                <v-text-field v-model="phone" :counter="10" label="Phone">
                </v-text-field>

                <!--<v-select v-model="select" :items="items" :rules="[v => !!v || 'Item is required']" label="Item" required>
        </v-select>-->

                <!--<v-checkbox v-model="checkbox" :rules="[v => !!v || 'You must agree to continue!']" label="Do you agree?"
            required></v-checkbox>-->
            </v-card-text>
            <v-card-actions>

                <v-btn :disabled="!valid" color="success" class="mr-4" @click="submit">
                    Submit
                </v-btn>

                <!-- <v-btn color="warning" class="mr-4" @click="reset">
                    Reset
                </v-btn> -->
                <v-btn variant="plain" @click="prePop()">
                    Populate
                </v-btn>

                <!--<v-btn color="warning" @click="resetValidation">
            Reset Validation
        </v-btn>-->
            </v-card-actions>
        </v-form>
    </v-card>
</template>

<style lang="scss" scoped>
.branded {
    color: #75CAAA;
}
</style>