<script setup>
import { useAnalytics } from '~/stores/analytics.js'
import firstNames from '~/static/json/firstNames.json'
import lastNames from '~/static/json/lastNames.json'
const analytics = useAnalytics()

const form = ref(null)
const valid = ref(true)
const fname = ref('')
const lname = ref('')
const name = computed(() => fname.value + ' ' + lname.value)
const nameRules = [
    v => !!v || 'Name is required',
    v => (v && v.length <= 10) || 'Name must be less than 10 characters',
]
const email = ref('')
const emailRules = [
    v => !!v || 'E-mail is required',
    v => /.+@.+\..+/.test(v) || 'E-mail must be valid',
]

const phone = ref('')

const phoneRules = [
    v => !!v || 'Phone is required',
    v => /^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/.test(v) || 'Phone must be valid',
]

/*const select = ref(null)
const items = [
    'Item 1',
    'Item 2',
    'Item 3',
    'Item 4',
]
const checkbox = ref(false)*/

const traitsObject = computed(() => {
    return {
        fname: fname.value,
        lname: lname.value,
        name: name.value,
        email: email.value,
        phone: phone.value
    }
})

const user_id = computed(() => fname.value + '_' + lname.value + '_id') // would be generated by backend db

function prePop() {
    fname.value = 'Andy'
    lname.value = 'Cogbill'
    email.value = 'andycogbill@gmail.com'
    phone.value = "608-788-7808"
}

function randomInt(max) {
    return Math.ceil(Math.random() * max);
}

function randomPhoneNumber() {
    let result = '';
    let i = 0;

    do {
        result += (i === 3 || i === 7) ? '-' : `${randomInt(9)}`
        i = i + 1;
    } while (i < 12);

    return result
}

function prePopRandom() {
    const firstName = firstNames[randomInt(firstNames.length - 1)]
    const lastName = lastNames[randomInt(lastNames.length - 1)]
    fname.value = firstName
    lname.value = lastName
    email.value = (firstName + lastName + '@gmailx.com').toLowerCase()
    phone.value = randomPhoneNumber()
}

function submit() {
    if (form.value.validate()) {
        analytics.identify(user_id.value, traitsObject.value, true)
        analytics.track("User Registered")
    } else {
        // go to error page
    }
}

function reset() {
    form.value.reset()
}

function resetValidation() {
    form.value.resetValidation()
}


</script>

<template>
    <v-card>
        <v-card-title>Register</v-card-title>
        <v-form ref="form" v-model="valid" lazy-validation>
            <v-card-text>
                <v-text-field v-model="fname" :counter="10" :rules="nameRules" label="First Name" required>
                </v-text-field>

                <v-text-field v-model="lname" :counter="10" :rules="nameRules" label="Last Name" required>
                </v-text-field>

                <v-text-field v-model="email" :rules="emailRules" label="E-mail" required></v-text-field>

                <v-text-field v-model="phone" :rules="phoneRules" label="Phone" required></v-text-field>

                <!--<v-select v-model="select" :items="items" :rules="[v => !!v || 'Item is required']" label="Item" required>
        </v-select>-->

                <!--<v-checkbox v-model="checkbox" :rules="[v => !!v || 'You must agree to continue!']" label="Do you agree?"
            required></v-checkbox>-->
            </v-card-text>
            <v-card-actions>

                <v-btn :disabled="!valid" color="success" class="mr-4" @click="submit">
                    Submit
                </v-btn>

                <v-btn color="warning" class="mr-4" @click="reset">
                    Reset
                </v-btn>
                <v-btn variant="plain" @click="prePopRandom()">
                    Random
                </v-btn>

                <!--<v-btn color="warning" @click="resetValidation">
            Reset Validation
        </v-btn>-->
            </v-card-actions>
        </v-form>
    </v-card>


</template>

<style lang="scss" scoped>

</style>